<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfcUserLdap\Module'                            => __DIR__ . '/Module.php',
    'ZfcUserLdap\Authentication\Adapter\Ldap'       => __DIR__ . '/src/ZfcUserLdap/Authentication/Adapter/Ldap.php',
    'ZfcUserLdap\Entity\User'                       => __DIR__ . '/src/ZfcUserLdap/Entity/User.php',
    'ZfcUserLdap\Mapper\User'                       => __DIR__ . '/src/ZfcUserLdap/Mapper/User.php',
    'ZfcUserLdap\Options\ModuleOptions'             => __DIR__ . '/src/ZfcUserLdap/Options/ModuleOptions.php',
    'ZfcUserLdap\Service\LdapService'               => __DIR__ . '/src/ZfcUserLdap/Service/LdapService.php',
    'ZfcUserLdap\ServiceFactory\LdapServiceFactory' => __DIR__ . '/src/ZfcUserLdap/ServiceFactory/LdapServiceFactory.php',
);