<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ZfcUserLdap\Module'                                        => __DIR__ . '/Module.php',
  'ZfcUserLdap\Adapter\Ldap'                                  => __DIR__ . '/src/ZfcUserLdap/Adapter/Ldap.php',
  'ZfcUserLdap\Authentication\Adapter\LdapAuth'               => __DIR__ . '/src/ZfcUserLdap/Authentication/Adapter/LdapAuth.php',
  'ZfcUserLdap\Entity\User'                                   => __DIR__ . '/src/ZfcUserLdap/Entity/User.php',
  'ZfcUserLdap\Mapper\User'                                   => __DIR__ . '/src/ZfcUserLdap/Mapper/User.php',
  'ZfcUserLdap\Mapper\UserHydrator'                           => __DIR__ . '/src/ZfcUserLdap/Mapper/UserHydrator.php',
  'ZfcUserLdap\Provider\Identity\LdapIdentityProvider'        => __DIR__ . '/src/ZfcUserLdap/Provider/Identity/LdapIdentityProvider.php',
  'ZfcUserLdap\Provider\Identity\ZfcRbacIdentityProvider'     => __DIR__ . '/src/ZfcUserLdap/Provider/Identity/ZfcRbacIdentityProvider.php',
  'ZfcUserLdap\ServiceFactory\LdapAdapterFactory'             => __DIR__ . '/src/ZfcUserLdap/ServiceFactory/LdapAdapterFactory.php',
  'ZfcUserLdap\ServiceFactory\LdapConfigFactory'              => __DIR__ . '/src/ZfcUserLdap/ServiceFactory/LdapConfigFactory.php',
  'ZfcUserLdap\Service\LdapIdentityProviderFactory'           => __DIR__ . '/src/ZfcUserLdap/ServiceFactory/LdapIdentityProviderFactory.php',
  'ZfcUserLdap\ServiceFactory\LoggerAdapterFactory'           => __DIR__ . '/src/ZfcUserLdap/ServiceFactory/LoggerAdapterFactory.php',
  'ZfcUserLdap\ServiceFactory\UserMapperFactory'              => __DIR__ . '/src/ZfcUserLdap/ServiceFactory/UserMapperFactory.php',
  'ZfcUserLdap\ServiceFactory\ZfcRbacIdentityProviderFactory' => __DIR__ . '/src/ZfcUserLdap/ServiceFactory/ZfcRbacIdentityProviderFactory.php',
  'ZfcUserLdap\ServiceFactory\ZfcUserLdapConfigFactory'       => __DIR__ . '/src/ZfcUserLdap/ServiceFactory/ZfcUserLdapConfigFactory.php',
  'ZfcUserLdapTest\ServiceFactory\LdapAdapterFactoryTest'     => __DIR__ . '/tests/ZfcUserLdapTest/src/ServiceFactory/LdapAdapterFactoryTest.php',
);
